name: Deploy to Pantheon
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Deploy to Pantheon
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        git remote add pantheon $pantheon_repo
        git push --force pantheon HEAD:refs/heads/$BASE_BRANCH

    - name: Launch Multidev
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        terminus multidev:create ${{ secrets.PANTHEON_SITE }}.live $BASE_BRANCH